# Generated by Django 4.0.3 on 2022-04-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_estoque', '0006_produto_quantidade_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='lucro',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_vendido',
            field=models.IntegerField(default='0'),
        ),
    ]
