# Generated by Django 4.0.3 on 2022-05-08 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_de_estoque', '0007_produto_lucro_alter_produto_quantidade_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='lucro',
            field=models.FloatField(default='0'),
        ),
    ]
